### ISSUE TITLE
Wrapping Prev / Next around Icon Boundaries

### ISSUE THREAD

**Issue by Cecilectomy** [clockworkpi/launcher#175]
Can we get wrapping icon movement in the launcher? Wrapping to the beginning and end of the icons provides better usability.

**Comment by Cecilectomy** [comment]
Created pull request: https://github.com/clockworkpi/launcher/issues/175#issue-414771555

**Comment by cuu** [comment]
Merged

thanks man

**Comment by Cecilectomy** [comment]
Awesome
