### ISSUE TITLE
Pico-8 won't install if not in compkginfo.json

### ISSUE THREAD

**Issue by Cecilectomy** [clockworkpi/launcher#182]
Currently pico-8 will not be installable via the pico-8*raspi.zip files if the desired version does not have an entry in compkginfo.json.

**example**: _currently trying to install pico-8_0.1.12c_raspi.zip does not work as it has no entry in compkginfo.json._

I propose that the install process installs ANY version of pico-8 using a pattern match for something like "pico-8*raspi.zip" and if there is not corresponding entry in compkginfo.json with an md5 checksum, it displays the validation warning and lets the user install anyways.

This would make installation of pico-8 easier for the end user without confusion as to why it wont install or work as well as remove the need for always having the latest launcher or modifying launcher files.

**Comment by cuu** [comment]
ok,sure,marked
thanks

**Comment by mguilherme** [comment]
I've added this #184 that adds the latest pico-8 version while we don't have another option.

**Comment by cuu** [comment]
now has a simple solution,just rename any downloaded zip file to `pico-8.zip` and it can start to install

**Comment by Cecilectomy** [comment]
Thanks @cuu! I'll close this issue, but CommercialPackageSoftware/__init__.py should still be able to install even if the zip is not in the compkginfo.json. Maybe by adding a fallback file pattern to compkginfo.json for installation if none exists in the MD5 map. This would allow any "CommercialPackageSoftware" to provide a fallback for installing versions not yet added with an MD5. A new issue can be created for this if and when needed.
