### ISSUE TITLE
视频播放器有计划开发吗？(do you have plan to develop a video player)

### ISSUE THREAD

**Issue by hyuans** [clockworkpi/launcher#270]
i think it is interesting to play a video in gameshell，i hope it will be real

**Comment by TomomiSawako** [comment]
Maybe use [Python + LibVLC](https://wiki.videolan.org/LibVLC/) can make a simple player.
But i think official Launcher now need App Package management for easy install & remove third-party app.
Python + LibVLC 应该可以做一个播放器，不过我认为官方 Launcher 现在更需要一个 App 包管理器来方便大家扩充App。

**Comment by hyuans** [comment]
> Maybe use [Python + LibVLC](https://wiki.videolan.org/LibVLC/) can make a simple player.
> But i think official Launcher now need App Package management for easy install & remove third-party app.
> Python + LibVLC 应该可以做一个播放器，不过我认为官方 Launcher 现在更需要一个 App 包管理器来方便大家扩充App。

can i use python 3 to develop? 
i am not a python developer,but i think i will learn python,and try to develop this app. 
but now i want to know how to install a self-developed app

我能用python3开发吗?
我不是一个python开发者,但我想尝试去学习这块的开发
但是当下我是很好奇怎样去安装一个自己开发的应用

**Comment by shar0** [comment]
If you have any experience of programming, it will not too hard start from 0. Official Launcher (Music Player)[https://github.com/clockworkpi/launcher/tree/master/Menu/GameShell/97_Music%20Player] is a good example, and Official Launcher use Python 2.7.
如果你有过其他语言编程经验，学起来应该不会太难，可以参考本项目的 Music Player 。另外本项目用了 Python 2.7。

**Comment by hyuans** [comment]
> If you have any experience of programming, it will not too hard start from 0. Official Launcher
> [Music Player](https://github.com/clockworkpi/launcher/tree/master/Menu/GameShell/97_Music%20Player)
> is a good example, and Official Launcher use Python 2.7.
> 如果你有过其他语言编程经验，学起来应该不会太难，可以参考本项目的 Music Player 。另外本项目用了 Python 2.7。

Does it mean i must use Python2.7 to develop，not Python3
那是不是意味着我必须用Python2.7来开发，Python3没法开发是吧

**Comment by shar0** [comment]
> > If you have any experience of programming, it will not too hard start from 0. Official Launcher
> > [Music Player](https://github.com/clockworkpi/launcher/tree/master/Menu/GameShell/97_Music%20Player)
> > is a good example, and Official Launcher use Python 2.7.
> > 如果你有过其他语言编程经验，学起来应该不会太难，可以参考本项目的 Music Player 。另外本项目用了 Python 2.7。
> 
> Does it mean i must use Python2.7 to develop，not Python3
> 那是不是意味着我必须用Python2.7来开发，Python3没法开发是吧

You can use Python 3 both with Python 2.7 in your own project. Use Python 2.7 is just for Extend this Launcher (It's mean you want Add an Icon with Text in GameShell Main Menu, you must write some Python 2.7 code), and Launch your Python 3 project in other process (Because GameShell is based on Linux anythings you can do in Raspberry Pi, its also work in GS too).

你可以同时用 Py3 和 Py2.7 来开发你自己的项目，Py 2.7 相关的代码只是用来扩展本项目（即Launcher），也就是说如果你想在GS的主菜单加个图标&文字，你就得写些Py2.7代码，然后再用这些代码开启一个新的进程来启动你的Py3程序，GS是基于Linux的，所以任何你能在树莓派上做的事情，GS也可以。

**Comment by hyuans** [comment]
> > > If you have any experience of programming, it will not too hard start from 0. Official Launcher
> > > [Music Player](https://github.com/clockworkpi/launcher/tree/master/Menu/GameShell/97_Music%20Player)
> > > is a good example, and Official Launcher use Python 2.7.
> > > 如果你有过其他语言编程经验，学起来应该不会太难，可以参考本项目的 Music Player 。另外本项目用了 Python 2.7。
> > 
> > 
> > Does it mean i must use Python2.7 to develop，not Python3
> > 那是不是意味着我必须用Python2.7来开发，Python3没法开发是吧
> 
> You can use Python 3 both with Python 2.7 in your own project. Use Python 2.7 is just for Extend this Launcher (It's mean you want Add an Icon with Text in GameShell Main Menu, you must write some Python 2.7 code), and Launch your Python 3 project in other process (Because GameShell is based on Linux anythings you can do in Raspberry Pi, its also work in GS too).
> 
> 你可以同时用 Py3 和 Py2.7 来开发你自己的项目，Py 2.7 相关的代码只是用来扩展本项目（即Launcher），也就是说如果你想在GS的主菜单加个图标&文字，你就得写些Py2.7代码，然后再用这些代码开启一个新的进程来启动你的Py3程序，GS是基于Linux的，所以任何你能在树莓派上做的事情，GS也可以。

thank you for your answer，but i have a few question
in  the 97_Music Player folder，which py file must be write by py2.7？ __init__.py ？Is the entrance to the call？
I do not really know how to add an Icon with Text in GameShell Main Menu？
谢谢大佬的回答，但我还是有些问题
在97_Music Player这个文件夹里，哪个py文件是一定要用py2.7写的，是__init__.py吗？它是进入菜单时调用的入口吗？
我现在还是不是太清楚如何在GS的主菜单加个图标和文字的步骤

**Comment by calvinweb** [comment]
menu目录下可添加vlc

**Comment by cuu** [comment]
https://forum.clockworkpi.com/t/lightweight-video-viewer-not-kodi-for-viewing-local-video-files/4049/6

we have no plan to develop a video player right now,sorry
