### ISSUE TITLE
Gameshell launcher on RPI

### ISSUE THREAD

**Issue by ljacobo** [clockworkpi/launcher#305]
Hi, 

is it possible to install the launcher on a raspberry pi?

how can be done?

thanks.

**Comment by cuu** [comment]
yes , absolutely possible
cause the launcher and the whole GameShell os is just a pure linux(debian arm  stable),

try to setup the whole launcher on any linux (PC or Arm) through the README

All you just need to know a little bit about the basics of Linux

**Comment by ljacobo** [comment]
Thnks
