### ISSUE TITLE
Run Launcher on a (desktop) dev machine?

### ISSUE THREAD

**Issue by uvwxy** [clockworkpi/launcher#326]
I know this is not an issue, but as close to the devs as I can get ;)

Is there a way to run the launcher on a desktop/emulator/vm to make development faster?

I was thinking about playing with the code, but sending the files via my (rather slow) wifi, and relaunching it on the cpi is a bit tedious.

Is there a better way to develop stuff for the launcher?

Thanks in advance,
Paul

**Comment by cuu** [comment]
sure
I always set the launcher dev env in a vmware with debian 10 
I think other linuxs will work,too

**Comment by WangTingZheng** [comment]
> sure
> I always set the launcher dev env in a vmware with debian 10
> I think other linuxs will work,too

I tried to run launcher in my ubuntu, but it failed, more information in [here](https://forum.clockworkpi.com/t/how-to-run-gameshell-launcher-in-ubuntu/5507), Did I do some wrong? How can I fix that?

**Comment by cuu** [comment]
hi 
try 
```
sudo apt install python-gi  
pip install PyGObject
```

**Comment by WangTingZheng** [comment]
> hi
> try
> 
> ```
> sudo apt install python-gi  
> pip install PyGObject
> ```

hi, thanks to help me, still have bug:
```shell
(launcher) cpi@wangtingzheng-TM1701:~/apps/launcher/sys.py$ apt list python-gi
正在列表... 完成
python-gi/focal,focal 3.36.0-1 amd64
python-gi/focal,focal 3.36.0-1 i386
(launcher) cpi@wangtingzheng-TM1701:~/apps/launcher/sys.py$ pip list
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Package      Version 
------------ --------
dbus-python  1.2.16  
decorator    4.4.2   
pip          20.0.2  
pyalsaaudio  0.8.4   
pycairo      1.18.2  
pycurl       7.43.0.5
pygame       1.9.6   
PyGObject    3.36.0  
python-mpd   0.3.0   
setuptools   44.1.0  
six          1.14.0  
some-package 0.1     
validators   0.14.3  
wheel        0.34.2  
xlib         0.21    
```
error:
```
(launcher) cpi@wangtingzheng-TM1701:~/apps/launcher$ sudo ./load.sh
Traceback (most recent call last):
  File "run.py", line 10, in <module>
    from wicd import misc
  File "/usr/lib/python2.7/dist-packages/wicd/misc.py", line 30, in <module>
    import gobject
ImportError: No module named gobject
(launcher) cpi@wangtingzheng-TM1701:~/apps/launcher$ 
```

**Comment by WangTingZheng** [comment]
> hi
> try
> 
> ```
> sudo apt install python-gi  
> pip install PyGObject
> ```

should I use old version of PyGObject?

**Comment by cuu** [comment]
launcher is written by python2 , so I think to use pip to install PyGObject

**Comment by cuu** [comment]
and
```
sudo apt install wicd-daemon  wicd-curses python-wicd wicd wicd-cli
```

**Comment by WangTingZheng** [comment]
> launcher is written by python2 , so I think to use pip to install PyGObject

I had tried to install it by pip(python2), but still fail. I run hello.py in [pygobject offical document ](https://pygobject.readthedocs.io/en/latest/), I worked, but the offical demo uses `import gi` rather than `import gobject`:
```
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

window = Gtk.Window(title="Hello World")
window.show()
window.connect("destroy", Gtk.main_quit)
Gtk.main()
```
maybe `import gobject` was not supported in lastest version of gobject, so the I got this error, I think i have already install gobject in python2 ven

**Comment by cuu** [comment]
try to install the wicd stuff, it is related to wicd, and launcher use the wicd as wifi backend

**Comment by WangTingZheng** [comment]
> try to install the wicd stuff, it is related to wicd, and launcher uses the wicd as wifi backend

can not install, I tried aptitude, should I change python2 version?
```
(gameshell_python_11) cpi@wangtingzheng-TM1701:~/桌面$ sudo apt install wicd-daemon  wicd-curses python-wicd wicd wicd-cli
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
有一些软件包无法被安装。如果您用的是 unstable 发行版，这也许是
因为系统无法达到您要求的状态造成的。该版本中可能会有一些您需要的软件
包尚未被创建或是它们已被从新到(Incoming)目录移出。
下列信息可能会对解决问题有所帮助：

下列软件包有未满足的依赖关系：
 python-wicd : 依赖: python:any (< 2.8)
               依赖: python:any (>= 2.7.5-5~)
 wicd-cli : 依赖: python:any (>= 2.7.5-5~)
 wicd-curses : 依赖: python-urwid (>= 1.1) 但是它将不会被安装
               依赖: python:any (>= 2.7.5-5~)
 wicd-daemon : 依赖: python:any (>= 2.7.5-5~)
E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系。
(gameshell_python_11) cpi@wangtingzheng-TM1701:~/桌面$ 
```

**Comment by cuu** [comment]
最好用python2的环境，launcher不兼容python3

我在ubuntu19.10里试了一下 
`sudo apt install wicd-daemon  wicd-curses python-wicd wicd wicd-cli`
可以安装
最好不好用conda之类的工具，
launcher当时没有用到虚拟环境，所以尽可能不要用conda之类的工具
在新的ubuntu上安装wicd还会碰到apt安装时wicd-daemon起不来的问题，在手动解决，wicd比较老了没人在维护

-----------------------------
it is best to use python2 ,launcher is not compatible with python3
I tried it in ubuntu19.10 
`sudo apt install wicd-daemon wicd-curses python-wicd wicd wicd-cli` 

It's better not to use tools like conda, The launcher did not use a virtual environment at the time, so try not to use tools such as conda

Installing wicd on a new ubuntu will also encounter the problem that wicd-daemon won't get up during apt installation. When manually solved, wicd is old and no one is maintaining it

![Screen Shot 2020-04-15 at 1 06 51 AM](https://user-images.githubusercontent.com/523580/79253628-1b933000-7eb6-11ea-93cd-1de445b6790d.png)

**Comment by WangTingZheng** [comment]
> 最好用python2的环境，launcher不兼容python3
> 
> 我在ubuntu19.10里试了一下
> `sudo apt install wicd-daemon wicd-curses python-wicd wicd wicd-cli`
> 可以安装
> 最好不好用conda之类的工具，
> launcher当时没有用到虚拟环境，所以尽可能不要用conda之类的工具
> 在新的ubuntu上安装wicd还会碰到apt安装时wicd-daemon起不来的问题，需要手动解决，wicd比较老了没人在维护
> 
> it is best to use python2 ,launcher is not compatible with python3
> I tried it in ubuntu19.10
> `sudo apt install wicd-daemon wicd-curses python-wicd wicd wicd-cli`
> 
> It's better not to use tools like conda, The launcher did not use a virtual environment at the time, so try not to use tools such as conda
> 
> Installing wicd on a new ubuntu will also encounter the problem that wicd-daemon won't get up during apt installation. Required to manually solve, wicd is old and no one is maintaining it
> 
> ![Screen Shot 2020-04-15 at 1 06 51 AM](https://user-images.githubusercontent.com/523580/79253628-1b933000-7eb6-11ea-93cd-1de445b6790d.png)

感谢您的耐心指导，看来我的软件依赖有点问题，即使我使用`aptitude`都无法修复，可能之前的操作打乱了软件依赖关系，我有时间再整整，这东西太消磨人的耐心了。

Thank you for your patience. It seems that my software dependency is a little bit problematic. Even if I use 'aptitude', I can't fix it. Maybe the previous operation has disrupted the software dependency. I will try to fix that when I have spare time . It's too wearing away people's patience.
