### ISSUE TITLE
retroarch-local.cfg doesn't do anything

### ISSUE THREAD

**Issue by briangordon** [clockworkpi/launcher#327]
The [release notes for 1.22](https://github.com/clockworkpi/launcher/releases/tag/1.22) says:

> Auto detect retroarch-local.cfg under launcher/20_Retro\ Games/[MGBA,MAME,NESTOPIA,etc...] to use as custom seperated retroarch config file, so that we can feel free to define retroarch's behaviour,like key mapping

But it doesn't look like this was ever merged. 

https://github.com/clockworkpi/launcher/compare/1.21...1.22

**Comment by cuu** [comment]
you mean there is no Auto detect retroarch-local.cfg function in 1.22?
if that so, my mistake,sorry
try use newer version
thanks
