### ISSUE TITLE
Add a reboot option on the launcher

### ISSUE THREAD

**Issue by MrP1xel** [clockworkpi/launcher#58]
Hello, only power off option is available from the launcher, can you add a reboot option in the poweroff script ?

     def KeyDown(self,event):
        
        if event.key == CurKeys["Menu"] or event.key == CurKeys["A"]:
            
            self.ReturnToUpLevelPage()
            self._Screen.Draw()
            self._Screen.SwapAndShow()

        if event.key == CurKeys["B"]:
            if self.CheckBattery() < 20:
                cmdpath = "feh --bg-center gameshell/wallpaper/gameover.png;"
            else:
                cmdpath = "feh --bg-center gameshell/wallpaper/seeyou.png;"
            
            cmdpath += "sleep 3;"
            
            #cmdpath += "echo 'halt -p' > /tmp/halt_cmd"
            
            cmdpath += "sudo halt -p"
            pygame.event.post( pygame.event.Event(RUNSYS, message=cmdpath))
            
        if event.key == CurKeys["X"]:

            cmdpath = "sudo reboot"
            pygame.event.post( pygame.event.Event(RUNSYS, message=cmdpath))

**Comment by MrP1xel** [comment]
class PowerOffConfirmPage(ConfirmPage):
    
    _ConfirmText = "Confirm Power OFF?"
    _FootMsg = ["Nav","Reboot","","Cancel","Shutdown"]

**Comment by MrP1xel** [comment]
credits : 
QuantumKraken from clockwork forum and MrP1xel

**Comment by cuu** [comment]
could you make a pull request?
thanks

**Comment by eashwar** [comment]
I believe this issue can be closed now since the PR has been merged into master.
