### ISSUE TITLE
MPD playlist titles are sometimes a list

### ISSUE THREAD

**Issue by follower46** [clockworkpi/launcher#76]
This was a pain to figure out, but MPD playlistinfo titles are sometimes a list instead of a string.
This will cause the entire UI to lock up and not resolve until the offending track has been removed from the playlist (which is impossible since the playlist will be reloaded even after a reboot).

We can either handle this by scrubbing the playlist list in the libs/MPD/poller playlist method and make sure it only returns a single string (by joining the title list elements together with commas) or handle the playlist title sometimes being a list in the Menus/GameShell/Music Player/play_list_page.py.

If you want to try reproducing you can use the same public domain song I was testing with:
https://ia800307.us.archive.org/34/items/MusopenCollectionAsFlac/Bach_GoldbergVariations/JohannSebastianBach-01-GoldbergVariationsBwv.988-Aria.flac

**Comment by cuu** [comment]
fixed
