### ISSUE TITLE
Allow Wifi passwords that are longer than the input field

### ISSUE THREAD

**Issue by baxerus** [clockworkpi/launcher#80]
Hi,

I'm on a Wifi with a very long password (yes, I know). I can not enter the whole password, so of course I can not join the Wifi ☹️. On all other devices I used before (from smartphone, over streaming stick, to computers), normally the input field simply scrolls while you add more chars.

Of course I know, that you textarea thing is a little more complicated

**Comment by baxerus** [comment]
I tried entering the password via SSH directly in the wicd config, but that also does not work, because it is impossible now to open the Wifi config.

That isn't very surprising, a assumed a 50/50 chance that it would work, but it isn't. So the fix is even more important for me, because my workaround isn't working ☹️

**Comment by follower46** [comment]
Ah, WPA2 has a hard limit of 63 characters.
The input has a limit of 40 characters. I have a simple idea of how to account for this.
I verified that the TextArea is only used by the Wifi page, so making a change should be relatively safe.

**Comment by follower46** [comment]
I've created https://github.com/clockworkpi/launcher/pull/83
Here's a video of it running: https://www.youtube.com/watch?v=dXO1Qf910bs

**Comment by baxerus** [comment]
Cool! And incredibly fast response! Whoa 👍 

Where can I get it for testing?

**Comment by baxerus** [comment]
Okay, I'm stupid and was to excited to look through you posts carefully. Of course I can simply look into you merge request. Or since it is merged already even simply get the master branch.

So everything that is left for me is to get my Wifi back running to get all this onto the device 😉

**Comment by baxerus** [comment]
Super cool! clockworkPi is great till now 😉 

Connected via another Wifi and updated to the new version (that is the commit with the merge of your code). And, yes, now it is working!

Many thanks 🎆 👍

**Comment by stephensaw** [comment]
Ah follower46 beat me to it. I was working on it, and had a different implementation, though won't accept as many characters as his implementation.

This is how it looks like

![](https://github.com/stephensaw/launcher/raw/feature/multiline-wifi-password/wifi-password-multiline.gif)

**Comment by follower46** [comment]
Woah! that's cool!
I wouldn't have thought of reducing the font size. Very cool idea
