### ISSUE TITLE
Enable Bluetooth Pairing

### ISSUE THREAD

**Issue by follower46** [clockworkpi/launcher#93]
Now that we have the bluetooth driver, it would be nice to be able to pair bluetooth devices from the launcher.

**Comment by cuu** [comment]
Will do

**Comment by cuu** [comment]
bluetooth alpha now
check out the newest code of launcher then you will see it 
and make sure you enabled bluetooth by 

[bluetooth wiki](https://github.com/clockworkpi/bluetooth/wiki)

and also could add auto-run for bluetooth by 
```
sudo su

cat <<EOF >/etc/rc.local
#!/bin/sh -e
sleep 15
brcm_patchram_plus --patchram /lib/firmware/brcm/bcm43438a0.hcd --enable_hci --bd_addr B0:F1:EC:2D:07:5B --no2bytes --tosleep 5000 /dev/ttyS1 &
EOF
chmod +x /etc/rc.local
systemctl daemon-reload
systemctl start rc-local
systemctl status rc-local

systemctl enable bluetooth
reboot
```

add two lines in   `/etc/systemd/system/dbus-org.bluez.service`  to prevent blueZ unexpected crash
```
Restart=always
RestartSec=3
```

[Service]  section
after this line `ProtectSystem=full`  

Happy Hacking
